#!/bin/sh

#DEBHELPER#

if [ "$1" = "configure" ]; then
	if [ -d /usr/doc -a ! -e /usr/doc/robotfindskitten -a -d /usr/share/doc/robotfindskitten ]; then
		ln -sf ../share/doc/robotfindskitten /usr/doc/robotfindskitten
	fi
fi

if [ "$1" = "configure" ]; then
	install-info --section Games Games --quiet /usr/share/info/robotfindskitten.info
fi

